apiVersion: apps/v1
kind: Deployment
metadata:
  name: basic-crud
  namespace: basic-crud
spec:
  replicas: 2
  selector:
    matchLabels:
      app: basic-crud
  template:
    metadata:
      labels:
        app: basic-crud
    spec:
      containers:
        - name: basic-crud
          image: atanasfinki/basic-crud:latest
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: basic-crud-config
            - secretRef:
                name: basic-crud-secrets
