apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: basic-crud-ingress
  namespace: basic-crud
spec:
  rules:
    - host: your-app-domain.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: basic-crud-service
                port:
                  number: 80
