apiVersion: v1
kind: Service
metadata:
  name: basic-crud-service
  namespace: basic-crud
spec:
  selector:
    app: basic-crud
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
