apiVersion: v1
kind: Secret
metadata:
  name: postgres-secrets
  namespace: basic-crud
type: Opaque
data:
  POSTGRES_USER: cG9zdGdyZXM=  # "postgres" base64 encoded
  POSTGRES_PASSWORD: cGFzc3dvcmQ=  # "password" base64 encoded
