version: '3.8'

services:
  db:
    image: postgres:15
    container_name: basic-crud_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: basic-crud
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - basic-crud_network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: basic-crud_app
    ports:
      - "8081:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/basic-crud
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    depends_on:
      - db
    networks:
      - basic-crud_network

networks:
  basic-crud_network:
    driver: bridge

volumes:
  db_data:
