name: CI/CD Pipeline

on:
  push:
    branches:
      - master
      - ci-cd-setup

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./Basic-Crud
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/basic-crud:latest

      - name: Deploy to Kubernetes
        if: github.ref == 'refs/heads/master' #set to an imaginary branch so that it gets ignored (I'm facing an unexpected problem with Kubernetes)
        run: |
          kubectl apply -f Basic-Crud/k8s/deployment.yml --validate=false
          kubectl apply -f Basic-Crud/k8s/service.yml --validate=false
          kubectl apply -f Basic-Crud/k8s/ingress.yml --validate=false
          kubectl apply -f Basic-Crud/k8s/statefulset.yml --validate=false
        working-directory: ${{ github.workspace }}
